<section class="list">
	<ul class="area">
		<li data-id="1288" class="area-li box start box-align">
			<div class="img-box box center">
				<div class="img-p">
					<img src="images/biao.png" r_src="#" />
				</div>
			</div>
			<div class="area-circle box start">
				<span class="name">北京车友圈</span>
				<span class="num">15151人</span>
			</div>
			<span class="focus">+关注</span>
		</li>
	</ul>
		<ul class="area">
		<li data-id="1288" class="area-li box start box-align">
			<div class="img-box box center">
				<div class="img-p">
					<img src="images/biao.png" r_src="#" />
				</div>
			</div>
			<div class="area-circle box start">
				<span class="name">北京车友圈</span>
				<span class="num">15151人</span>
			</div>
			<span class="focus">+关注</span>
		</li>
	</ul>
		<ul class="area">
		<li data-id="1288" class="area-li box start box-align">
			<div class="img-box box center">
				<div class="img-p">
					<img src="images/biao.png" r_src="#" />
				</div>
			</div>
			<div class="area-circle box start">
				<span class="name">北京车友圈</span>
				<span class="num">15151人</span>
			</div>
			<span class="focus">+关注</span>
		</li>
	</ul>
		<ul class="area">
		<li data-id="1288" class="area-li box start box-align">
			<div class="img-box box center">
				<div class="img-p">
					<img src="images/biao.png" r_src="#" />
				</div>
			</div>
			<div class="area-circle box start">
				<span class="name">北京车友圈</span>
				<span class="num">15151人</span>
			</div>
			<span class="focus">+关注</span>
		</li>
	</ul>
		<ul class="area">
		<li data-id="1288" class="area-li box start box-align">
			<div class="img-box box center">
				<div class="img-p">
					<img src="images/biao.png" r_src="#" />
				</div>
			</div>
			<div class="area-circle box start">
				<span class="name">北京车友圈</span>
				<span class="num">15151人</span>
			</div>
			<span class="focus">+关注</span>
		</li>
	</ul>
</section>